### ISSUE TITLE
Error when using filler_regex_and_list

### ISSUE THREAD

**Issue by nickduran** [nickduran/align-linguistic-alignment#48]
Please remove Line 73 in prepare_transcripts.py. Seems to be old code and is throwing an error. I tested without the line on local version (setting filler_regex_and_list=True and supplying a list of additional filler words) and program works as it is supposed to (filters out regular expressions and user-supplied list).

**Comment by a-paxton** [comment]
Thanks! Will be pushing something shortly to address this.
