### ISSUE TITLE
bug fix needed for version 8: "Processing:" printed to screen in prepare_transcripts needs to occur before reading file

### ISSUE THREAD

**Issue by nickduran** [nickduran/align-linguistic-alignment#49]
BUG FIX: Swap `print(("Processing: "+fileName))` line in `prepare_transcripts` function so it occurs before reading in the `pd.read_csv` of that file; if error with reading .csv then the wrong file is displayed to user

**Comment by a-paxton** [comment]
Fixed in recent commit.
